spring.application.name=AuthService
server.port=8081
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# MySQL (auto create DB)
spring.datasource.url=jdbc:mysql://caboose.proxy.rlwy.net:54143/toibidalieu?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=SOlcMKenlFlvtOKJeJYyVLIdmnyjLQrW
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# JWT
jwt.secret=U29tZV9zdXBlcl9zZWN1cmVfYW5kX2xvbmdfYmFzZTY0X2VuY29kZWRfc2VjcmV0X2tleV9mb3JfSlNXVDEyMw==
jwt.access-expiration-ms=9000000000
jwt.refresh-expiration-ms=12096000000000

# Google OAuth
google.client-ids=YOUR_WEB_CLIENT_ID.apps.googleusercontent.com,ANOTHER_CLIENT_ID.apps.googleusercontent.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=doantn20255@gmail.com
spring.mail.password=dfvffkbotltropjq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.security.oauth2.client.registration.google.client-id=805426471815-fm6ism94ih9441gnvfkluvofeke95dc2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=openid,profile,email

#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

app.mail.from=doantn20255@gmail.com

server.error.include-message=always

spring.mail.test-connection=false
# --- OTP policy ---
otp.register.ttl-seconds=300
otp.reset.ttl-seconds=300
otp.resend.cooldown-seconds=60
otp.max-attempts=5

# ================== VNPAY CONFIG ==================
vnpay.tmnCode=6198HXFD
vnpay.hashSecret=X4WV364UTHTGI7OR0JQP1B6ZLNPV3FCI
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#vnpay.returnUrl=http://localhost:8080/api/payments/vnpay/return
vnpay.returnUrl=http://10.0.2.2:8080/api/payments/vnpay/return

vnpay.refundUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

#Test Info
#NCB
#9704198526191432198
#NGUYEN VAN A
#07/15

cloudinary.cloud-name=dn9slxnjb
cloudinary.api-key=359329663246449
cloudinary.api-secret=RFsY2YDwjKTZH-8Ed9GF1jG2_V0

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
