# ===============================
#  Environment: PRODUCTION (Render) - Profile: pro
# ===============================

spring.application.name=AuthService

server.port=${PORT:8080}

# MySQL (auto create DB)
spring.datasource.url=jdbc:mysql://caboose.proxy.rlwy.net:54143/toibidalieu?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=SOlcMKenlFlvtOKJeJYyVLIdmnyjLQrW
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# JWT
jwt.secret=U29tZV9zdXBlcl9zZWN1cmVfYW5kX2xvbmdfYmFzZTY0X2VuY29kZWRfc2VjcmV0X2tleV9mb3JfSlNXVDEyMw==
jwt.access-expiration-ms=900000
jwt.refresh-expiration-ms=1209600000
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Google OAuth
google.client-ids=YOUR_WEB_CLIENT_ID.apps.googleusercontent.com,ANOTHER_CLIENT_ID.apps.googleusercontent.com

# ======================================================
#  MAILTRAP EMAIL API (thay cho spring.mail.*)
# ======================================================
mailtrap.api.url=https://send.api.mailtrap.io/api/send
mailtrap.api.token=${MAILTRAP_API_TOKEN}
mailtrap.from.email=no-reply@demomailtrap.com
mailtrap.from.name=AuthService

app.mail.from=${mailtrap.from.email}

spring.mail.test-connection=false

# --- OTP policy ---
otp.register.ttl-seconds=300
otp.reset.ttl-seconds=300
otp.resend.cooldown-seconds=60
otp.max-attempts=5
